# Form implementation generated from reading ui file '.\QtUI\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(parent=self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 0, 600, 450))
        self.image.setText("")
        self.image.setObjectName("image")
        self.switchThemeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.switchThemeButton.setGeometry(QtCore.QRect(610, 0, 190, 40))
        self.switchThemeButton.setObjectName("switchThemeButton")
        self.searchTextLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.searchTextLabel.setGeometry(QtCore.QRect(610, 60, 190, 40))
        self.searchTextLabel.setObjectName("searchTextLabel")
        self.searchObjectLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.searchObjectLineEdit.setGeometry(QtCore.QRect(610, 100, 190, 40))
        self.searchObjectLineEdit.setObjectName("searchObjectLineEdit")
        self.searchObjectButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchObjectButton.setGeometry(QtCore.QRect(610, 150, 190, 40))
        self.searchObjectButton.setObjectName("searchObjectButton")
        self.clearObjectButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearObjectButton.setGeometry(QtCore.QRect(610, 200, 190, 40))
        self.clearObjectButton.setObjectName("clearObjectButton")
        self.fullAddressLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.fullAddressLabel.setGeometry(QtCore.QRect(610, 250, 190, 70))
        self.fullAddressLabel.setText("")
        self.fullAddressLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.fullAddressLabel.setWordWrap(True)
        self.fullAddressLabel.setObjectName("fullAddressLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.switchThemeButton.setText(_translate("MainWindow", "Сменить тему"))
        self.searchTextLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Поиск объекта</span></p></body></html>"))
        self.searchObjectButton.setText(_translate("MainWindow", "Искать"))
        self.clearObjectButton.setText(_translate("MainWindow", "Сброс"))
